= Innopolis University MAP-S21 Project
:status: bottom
:inclusion:
:experimental:
// ------------------------------------------
:icons: font


// Specific to GitHub
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


== Context
A simple database management system which designed to manage hospital. The system should be able to keep track of the records of the doctors, patients, nurses, and other hospital staff. The main aim is to minimize the paperwork of the hospital as minimum as possible, if not completely. 

== Technologies stack
. Database - PostgreSQL
. Database management - Java/Python
. User Interface - Java
. Tests - Python

== Initial Product Backlog

:numbered!:
===  Initial Client Features

The initial functionalities requested are as follows:

. Multi user account system
. Monitoring the whole hospital system
. Management of all types of users’ account
. Notice Board
. Appointment Management
. View Appointments
. Notifications
. Medical History
. Invoice Management
. Medical Report Management
. Internal Communication
. Responsive User Interfaces

:numbered!:
==== User Stories
. As a user, I want to go to the profile page so that I see account information and future appointments 
. As a user, I want to get notifications about the future appointments so that I remember about them 
. As a patient, I want to see the schedule of the doctors so that I can match my schedule with the doctor's schedule
. As a patient, I want to setup/cancel an appointment with the needed doctor so that I can go for treatment
. As a patient, I want to get the medical certificate so that I can get sick leave
. As a doctor, I want to see the upcoming appointments so that I can prepare for the patient
. As a doctor, I want to edit patient history so that I won't forget what happen to the patient
. As a receptionist, I want to create patient history so that each patient will have one
. As a receptionist, I want to assign call to the ambulance so that it can provide fast emergency help


:numbered!:
== Team
. Alfiya Musabekova <a.musabekova@innopolis.university>
. Renat Valeev <r.valeev@innopolis.university>
. Marina Nikolaeva <m.nikolaeva@innopolis.university>

:numbered!:
== Useful links

- The materials for the course: http://bit.ly/innopolis-map
- Trello: https://trello.com/b/JTL05fyN
