BEGIN TRANSACTION;
drop table is_for;
drop table notification;
drop table report;
drop table medical_report;
drop table appointment;
drop table medical_certificate;
drop table invoice;
drop table patient;
drop table approved_request;
drop table required_request;
drop table request;
drop table message;
drop table member_of_chat;
drop table chat;
drop table content;
drop table web_page;
drop table salary;
drop table "user";
drop table ambulance;
drop table account;
drop table medicament;
drop table supply;
drop table department;
END TRANSACTION;
